### ISSUE TITLE
Implement the connect wallet window and add the connect functionality

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#2]
Implement a pixel perfect connect wallet window according to the provided [FIGMA Design](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=TD5fHZerbCxY8HMK-0)
Also implement connect functionality.

**Comment by PedroCo3lho** [comment]
Hello @Oshioke-Salaki, can I work on this issue? 
I plan to use [StarknetKit](https://www.starknetkit.com/) and manage the wallet configurations and functions in a `walletConfig.ts` file. I’ll then wrap it in `providers.tsx` to make it globally available throughout the app.

**Comment by Joy-Adah** [comment]
Hey @Oshioke-Salaki can I be assigned this? I am a frontend developer and I will have a draft PR ready as soon as possible.

**Comment by 0xdevcollins** [comment]
@Oshioke-Salaki, can I work on this?
 I am a Full Stack Blockchain Developer with expertise in Next.js, TypeScript, React, Node.js, and Solidity/Rust. With 46 contributions across 10 OnlyDust projects, I bring technical excellence, adaptability, and a focus on user-centric blockchain solutions.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I pick this up?

**Comment by Joy-Adah** [comment]
Hello. I'd love to take up this issue. I am a web3 developer and contributor. I'll have a draft PR ready as soon as possible.

**Comment by jsanchez556** [comment]
Hi,  my name is José Mario from Costa Rica, a Full stack developer with more than 15 years in development and a focus in TypeScript, JavaScript, Nodejs and React. Open Source projects are something I enjoy, and I am now learning Rust, Cairo and Solidity. About my learning and growth in the industry, I started doing ODHacks as early as version 7.0 due to my work with Dojo Coding. I am excited to utilize my wealth of experience and experience to new technologies to meet new challenges and deliver results.

How to tackle the feature:

Create Modal Component based on the  provided Figma design
Write CSS Styling for the modal to ensure that the design is pixel perfect as in the design made in Figma
Add Wallet Functionality(ethers?)
Test locally in order to confirm whether the aspect and connection of the wallet are working as expected

**Comment by abdegenius** [comment]
Would love to tackle this! I can comfortably handle this issues
